# Generated by Django 4.1.2 on 2022-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage1',
            name='age',
            field=models.IntegerField(),
        ),
    ]
